### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

### ISSUE THREAD

**Issue by mateusrangel** [MarcelJurtz/LifeCounter#37]
I found your app on f-droid and tried to study/run the code on android-studio but got the following error

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.marceljurtz.lifecounter/com.marceljurtz.lifecounter.views.Game.GameActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

**Comment by MarcelJurtz** [comment]
What did you do to get the error? I've started to migrate the app to kotlin but haven't finished yet. I think that should also be resolved when I'm done.

**Comment by mateusrangel** [comment]
I just cloned the repo, opened in android studio and pressed the run button

**Comment by mateusrangel** [comment]
I reverted to the tag 2.0.0 version and everything runs fine here.

**Comment by mateusrangel** [comment]
Here is the full log:

01/05 09:34:16: Launching 'app' on Pixel_3a_API_30_x86.
Install successfully finished in 788 ms.
$ adb shell am start -n "com.marceljurtz.lifecounter/com.marceljurtz.lifecounter.views.Game.GameActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 5513 on device 'Pixel_3a_API_30_x86 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.marceljurtz.lifecounter, PID: 5513
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.marceljurtz.lifecounter/com.marceljurtz.lifecounter.views.Game.GameActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
        at com.marceljurtz.lifecounter.views.Game.GameActivity.<init>(GameActivity.kt:47)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
I/Process: Sending signal. PID: 5513 SIG: 9

**Comment by MarcelJurtz** [comment]
Ah got it, thank you. I thought you had the version from the current fdroid release. The kotlin-migration is still work in progress. Should be in a separate branch, but this project didn't have any collaborators so I put it all in here. Any releases (see the tags) should work. The current state will be updated asap.

**Comment by mateusrangel** [comment]
ok thanks
